services:
    ngmore_legacy.field_type.childrenindexer:
        class: eZ\Publish\Core\FieldType\Null\Type
        parent: ezpublish.fieldType
        arguments: [ 'childrenindexer' ]
        tags:
            - {name: ezpublish.fieldType, alias: childrenindexer}

    ngmore_legacy.field_type.childrenindexer.converter:
        class: eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\NullConverter
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: childrenindexer, lazy: true, callback: '::create'}

    ngmore_legacy.field_type.childrenindexer.indexable:
        class: eZ\Publish\Core\FieldType\Unindexed
        tags:
            - {name: ezpublish.fieldType.indexable, alias: childrenindexer}
