parameters:
    ngmore_legacy.templating.converter.user.class: Netgen\Bundle\MoreLegacyBundle\Templating\Converter\UserConverter

services:
    ngmore_legacy.templating.converter.user:
        class: "%ngmore_legacy.templating.converter.user.class%"
        arguments:
            - "@ezpublish_legacy.kernel"
        tags:
            - {name: ezpublish_legacy.templating.converter, for: eZ\Publish\Core\Repository\Values\User\User}
