services:
    ngmore_legacy.templating.converter.user:
        class: Netgen\Bundle\MoreLegacyBundle\Templating\Converter\UserConverter
        public: false
        arguments:
            - "@ezpublish_legacy.kernel"
        tags:
            - {name: ezpublish_legacy.templating.converter, for: eZ\Publish\Core\Repository\Values\User\User}
