parameters:
    ngmore_legacy.content_view_provider.class: Netgen\Bundle\MoreLegacyBundle\Core\MVC\Legacy\View\Provider\Content

services:
    ngmore_legacy.content_view_provider:
        class: %ngmore_legacy.content_view_provider.class%
        parent: ezpublish_legacy.content_view_provider
        calls:
            - [setLocationViewProvider, [@ezpublish_legacy.location_view_provider]]
        tags:
            - {name: ezpublish.content_view_provider, priority: -254}
