services:
    netgen_site_legacy.legacy_mapper.configuration:
        class: Netgen\Bundle\SiteLegacyBundle\LegacyMapper\Configuration
        public: false
        arguments:
            - "@ezpublish.config.resolver.core"
        tags:
            - { name: kernel.event_subscriber }
