services:
    netgen_site_legacy.legacy_mapper.configuration:
        class: Netgen\Bundle\SiteLegacyBundle\LegacyMapper\Configuration
        public: false
        arguments:
            - "@ezpublish.config.resolver.core"
        tags:
            - { name: kernel.event_subscriber }

#    Legacy Stack fallback view providers for Site API views are disabled by default.
#    Enable them in your project if needed by copying two following service definitions:
#
#    netgen_site_legacy.site_api.content_view_provider:
#        class: eZ\Publish\Core\MVC\Legacy\View\Provider\Content
#        public: false
#        parent: ezpublish_legacy.view_provider
#        tags:
#            - { name: ezpublish.view_provider, type: 'Netgen\Bundle\EzPlatformSiteApiBundle\View\ContentView', priority: -205 }
#
#    netgen_site_legacy.site_api.location_view_provider:
#        class: eZ\Publish\Core\MVC\Legacy\View\Provider\Location
#        public: false
#        parent: ezpublish_legacy.view_provider
#        calls:
#            - [setRequestStack, ["@request_stack"]]
#        tags:
#            # Location view provider must have priority higher than content view provider to be able
#            # to match the location first, in case it exists in the view
#            - { name: ezpublish.view_provider, type: 'Netgen\Bundle\EzPlatformSiteApiBundle\View\ContentView', priority: -200 }
