services:
    netgen_site_legacy.legacy_mapper.configuration:
        class: Netgen\Bundle\SiteLegacyBundle\LegacyMapper\Configuration
        public: false
        arguments:
            - "@ezpublish.config.resolver.core"
        tags:
            - { name: kernel.event_subscriber }

    netgen_site_legacy.listener.disable_image_alias_notify:
        class: Netgen\Bundle\SiteLegacyBundle\EventListener\DisableImageAliasNotifyListener
        public: false
        tags:
            - { name: kernel.event_subscriber }
