services:
    netgen_site_legacy.templating.converter.user:
        class: Netgen\Bundle\SiteLegacyBundle\Templating\Converter\UserConverter
        public: false
        arguments:
            - "@ezpublish_legacy.kernel"
        tags:
            - { name: ezpublish_legacy.templating.converter, for: Ibexa\Core\Repository\Values\User\User }
