services:
    netgen_site_legacy.site_api.content_view_provider:
        class: eZ\Publish\Core\MVC\Legacy\View\Provider\Content
        public: false
        parent: ezpublish_legacy.view_provider
        tags:
            - { name: ibexa.view.provider, type: 'Netgen\Bundle\IbexaSiteApiBundle\View\ContentView', priority: -205 }

    netgen_site_legacy.site_api.location_view_provider:
        class: eZ\Publish\Core\MVC\Legacy\View\Provider\Location
        public: false
        parent: ezpublish_legacy.view_provider
        calls:
            - [setRequestStack, ["@request_stack"]]
        tags:
            # Location view provider must have priority higher than content view provider to be able
            # to match the location first, in case it exists in the view
            - { name: ibexa.view.provider, type: 'Netgen\Bundle\IbexaSiteApiBundle\View\ContentView', priority: -200 }
