{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<p>
Powered by <span class="edition-info">eZ Publish</span>.<br />
<a href="http://ez.no/ezpublish">eZ Publish</a> Copyright &copy; 1999-2014 <a href="http://ez.no">eZ Systems AS</a> and others.
</p>
